# Generated by Django 5.2.7 on 2025-10-11 18:23

import action_detection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=action_detection.models.video_upload_path),
        ),
    ]
